#!/bin/bash

set -eu

gem_args="--no-document --no-post-install-message"

case "${_RUBYGEMS_VERSION-"latest"}" in
  "latest")
    gem update $gem_args --system
  ;;
  *)
    gem update $gem_args --system $_RUBYGEMS_VERSION
  ;;
esac

case "${_BUNDLER_VERSION-"latest"}" in
  "latest")
    gem update bundler $gem_args
  ;;
  *)
    gem install bundler $gem_args --version $_BUNDLER_VERSION
  ;;
esac
