#!/bin/bash

set -eu

gem_args="--no-verbose --no-document"

case "${_RUBYGEMS_VERSION-"latest"}" in
  "latest")
    echo "Updating rubygems"
    retry --times 5 --sleep 5 gem update $gem_args --system
  ;;
  *)
    echo "Updating rubygems to $_RUBYGEMS_VERSION}"
    retry --times 5 --sleep 5 gem update $gem_args --system $_RUBYGEMS_VERSION
  ;;
esac

case "${_BUNDLER_VERSION-"latest"}" in
  "latest")
    echo "Updating bundler"
    retry --times 5 --sleep 5 gem update bundler $gem_args
  ;;
  *)
    echo "Updating bundler to $_BUNDLER_VERSION"
    retry --times 5 --sleep 5 gem install bundler $gem_args --version $_BUNDLER_VERSION
  ;;
esac
